server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/


spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: lyf-client    # 项目名称尽量用小写
  jpa:
    database: MYSQL
  datasource: #mysql
    url: jdbc:mysql:///account_book?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8 #数据库地址
    username: root #数据库用户名
    password: root   #数据库密码
    driverClassName: com.mysql.jdbc.Driver #mysql驱动包
    max-active: 20
    max-idle: 8
    min-idle: 8